# Dockerfile for React client

# Build react client
FROM node:14-alpine

# Default working directory be marketplace
WORKDIR /usr/src/marketplace/client

COPY package*.json ./

# copy local files to letseat folder
COPY . .

###  Installing dependencies
RUN yarn install --silent

# Build project
RUN yarn build

EXPOSE 3001

CMD ["yarn","start"]